before:
  hooks:
    - go mod download

builds:
  - id: artifacthub-gchat-updates
    main: ./cmd
    binary: artifacthub-gchat-updates
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le
 
release:
  prerelease: auto

signs:
- cmd: cosign
  stdin: '{{ .Env.COSIGN_PASSWORD }}'
  args:
  - "sign-blob"
  - "--key=cosign.key"
  - "--output-signature=${signature}"
  - "${artifact}"
  - "--yes" # needed on cosign 2.0.0+
  artifacts: all


docker_signs:
- artifacts: all
  stdin: '{{ .Env.COSIGN_PASSWORD }}'

dockers:
  -
    image_templates:
    - "ghcr.io/arldka/{{ .ProjectName }}:latest"
    - "ghcr.io/arldka/{{ .ProjectName }}:{{ .Summary }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"

changelog:
  use: github

  sort: asc

  # Max commit hash length to use in the changelog.
  #
  # 0: use whatever the changelog implementation gives you
  # -1: remove the commit hash from the changelog
  # any other number: max length.
  #
  # Default: 0.
  # Since: v1.11.2
  abbrev: -1

  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

  filters:
    # Commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
