name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - "*"
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-petra:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20.3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.52

