name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:

    permissions:
      contents: write
      packages: write
      issues: write

    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - 
        run: git fetch --force --tags

      - 
        name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      
      - run: go version

      -
        name: Cosign Private Key
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - 
        name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - 
        name: Check install!
        run: cosign version

      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 1.16
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}